// Objective-C API for talking to github.com/simonhorlick/bbolt/mobile Go package.
//   gobind -lang=objc github.com/simonhorlick/bbolt/mobile
//
// File is generated by gobind. Do not edit.

#ifndef __Mobile_H__
#define __Mobile_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class MobileBoltDB;

@interface MobileBoltDB : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(NSString* _Nullable)filepath;
- (void)close;
- (NSString* _Nonnull)path;
@end

FOUNDATION_EXPORT MobileBoltDB* _Nullable MobileNewBoltDB(NSString* _Nullable filepath);

#endif
